### ISSUE TITLE
Error with configure / compiler 

### ISSUE THREAD

**Issue by Kax-gen** [davetang/learning_vcf_file#1]
greetings! I'm trying to get this running but have an issue during the configure/compiling step. Config.log reports: 
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
InstalledDir: /Users/kax/miniconda2/envs/py3/bin
configure:2237: $? = 0
configure:2226: x86_64-apple-darwin13.4.0-clang -V >&5
clang-4.0: error: argument to '-V' is missing (expected 1 value)
clang-4.0: error: no input files
configure:2237: $? = 1
configure:2226: x86_64-apple-darwin13.4.0-clang -qversion >&5
clang-4.0: error: unknown argument: '-qversion'
clang-4.0: error: no input files
configure:2237: $? = 1
configure:2257: checking whether the C compiler works
configure:2279: x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs conftest.c  >&5
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
configure:2283: $? = 1
configure:2321: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "BCFtools"
| #define PACKAGE_TARNAME "bcftools"
| #define PACKAGE_VERSION "1.6"
| #define PACKAGE_STRING "BCFtools 1.6"
| #define PACKAGE_BUGREPORT "samtools-help@lists.sourceforge.net"
| #define PACKAGE_URL "http://www.htslib.org/"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2326: error: in `/Users/kax/bin/bcftools-1.6':
configure:2328: error: C compiler cannot create executables
See `config.log' for more details 

`
Any suggestions on what my next step should be? Thanks!

**Comment by davetang** [comment]
Hi there and sorry for the delay! If you want to generate the example files checkout https://github.com/davetang/learning_vcf_file/tree/master/benchmark where I use Conda (and Bioconda) to install all the necessary tools.
