### ISSUE TITLE
VIDEO TUTORIAL

### ISSUE THREAD

**Issue by vappiah** [davetang/learning_vcf_file#2]
Hi Dave,

I recently made a video tutorial on merging vcf files.  I used the instructions provided on your github page. I acknowledged you and also gave a link to this page. I would like to publish on youtube but want to check with you if its ok that I give the link to your website and the github page in the video.

Thanks

**Comment by davetang** [comment]
Hi @vappiah,

thank you for the acknowledgment! Definitely not a problem.

Cheers,
Dave

**Comment by vappiah** [comment]
Here is the video 
https://youtu.be/R5JzeVF9jf8
